<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\admin_theme\**" />
    <Compile Remove="wwwroot\images\champions\**" />
    <Content Remove="wwwroot\admin_theme\**" />
    <Content Remove="wwwroot\images\champions\**" />
    <EmbeddedResource Remove="wwwroot\admin_theme\**" />
    <EmbeddedResource Remove="wwwroot\images\champions\**" />
    <None Remove="wwwroot\admin_theme\**" />
    <None Remove="wwwroot\images\champions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".github\workflows\" />
    <Folder Include="Database\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://www.schemastore.org/artifacthub-repo.json" /></VisualStudio></ProjectExtensions>

</Project>
